[build]
command = "npm run build:app"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[template.environment]
NEXTAUTH_SECRET = "578948cc101464b82889fe7399da3658"
DATABASE_URL = "mysql://root@127.0.0.1:3306/wesbitty"
NEXTAUTH_URL = "wesbittyapp.netlify.app"
